local M = {}

local palette = require("miasma.palette")

M.setup = function()
  return {

    Normal = { fg = palette.fg, bg = palette.bg },
    Boolean = { fg = palette.olive },
    Changed = { fg = palette.brown },
    ColorColumn = { bg = palette.bg },
    Comment = { fg = palette.gray, italic = true },
    Constant = { fg = palette.orange },
    Cursor = { fg = palette.bg, bg = palette.fg },
    CursorColumn = { bg = palette.bg },
    CursorLine = { bg = palette.bg },
    CursorLineNr = { fg = palette.olive, bg = palette.bg, bold = true },
    Delimiter = { fg = palette.fg },
    DiagnosticDeprecated = { sp = palette.brown, strikethrough = true },
    DiagnosticError = { fg = palette.red },
    DiagnosticHint = { fg = palette.gold },
    DiagnosticInfo = { fg = palette.gold },
    DiagnosticOk = { fg = palette.olive },
    DiagnosticSignError = { fg = palette.red, bg = palette.bg },
    DiagnosticSignHint = { fg = palette.gold, bg = palette.bg },
    DiagnosticSignInfo = { fg = palette.gold, bg = palette.bg },
    DiagnosticSignWarn = { fg = palette.brown, bg = palette.bg },
    DiagnosticUnderlineError = { underline = true },
    DiagnosticUnderlineHint = { underline = true },
    DiagnosticUnderlineInfo = { underline = true },
    DiagnosticUnderlineOk = { underline = true },
    DiagnosticUnderlineWarn = { underline = true },
    DiagnosticUnnecessary = { fg = palette.gray, underline = true },
    DiagnosticVirtualTextError = { fg = palette.red },
    DiagnosticVirtualTextHint = { fg = palette.olive, bg = palette.bg },
    DiagnosticVirtualTextInfo = { fg = palette.olive, bg = palette.bg },
    DiagnosticVirtualTextWarn = { fg = palette.brown, bg = palette.bg },
    DiagnosticVirtualTextWarning = { fg = palette.fg },
    DiagnosticWarn = { fg = palette.brown },
    DiagnosticWarningFloating = { fg = palette.fg },
    DiffAdd = { fg = palette.bg, bg = palette.green },
    DiffAdded = { fg = palette.green, bg = palette.bg },
    DiffChange = { fg = palette.bg, bg = palette.brown },
    DiffDelete = { fg = palette.bg, bg = palette.red, bold = true },
    DiffLine = { fg = palette.gray },
    DiffRemoved = { fg = palette.red, bg = palette.bg },
    DiffText = { fg = palette.bg, bg = palette.gold, bold = true },
    Directory = { fg = palette.olive, bg = palette.bg },
    Error = { fg = palette.fg_gray, bg = palette.red },
    ErrorMsg = { fg = palette.red, bg = palette.bg },
    FloatShadow = { bg = palette.bg },
    FoldColumn = { fg = palette.gray, bg = palette.bg },
    Folded = { fg = palette.orange, bg = palette.bg },
    Function = { fg = palette.olive },
    GitSignsAdd = { fg = palette.green, bg = palette.bg },
    GitSignsDelete = { fg = palette.red, bg = palette.bg },
    IblIndent = { fg = palette.black_green, nocombine = true },
    IblScope = { fg = palette.black_yellow, nocombine = true },
    Identifier = { fg = palette.fg },
    Ignore = { fg = palette.gray_dark, underline = true },
    IncSearch = { fg = palette.bg, bg = palette.orange },
    Keyword = { fg = palette.green },
    LazyButton = { bg = palette.bg },
    LazyButtonActive = { fg = palette.bg, bg = palette.olive },
    LazyH1 = { fg = palette.olive, bg = palette.bg },
    LazyH2 = { fg = palette.olive, bg = palette.bg },
    LazyNormal = { bg = palette.bg },
    LazySpecial = { fg = palette.gold },
    LineNr = { fg = palette.gray, bg = palette.bg },
    LspBorderBG = { fg = palette.brown, bg = palette.bg },
    LspFloatWinNormal = { fg = palette.fg, bg = palette.black_yellow },
    LspReferenceRead = { fg = palette.green, sp = palette.orange, bold = true, undercurl = true },
    LspReferenceText = { fg = palette.fg, bg = palette.black_yellow, sp = palette.orange, bold = true, undercurl = true },
    LspSignatureActiveParameter = { sp = palette.yellow, bold = true, italic = true, underline = true },
    MasonHeader = { fg = palette.fg, bg = palette.bg },
    MasonHighlight = { fg = palette.olive, bg = palette.bg },
    MasonMuted = { fg = palette.gold, bg = palette.bg },
    MatchParen = { fg = palette.fg, bold = true, underline = true },
    ModeMsg = { bold = true },
    MoreMsg = { fg = palette.green, bold = true },
    NonText = { fg = palette.gray, bold = true },
    Number = { fg = palette.olive },
    NvimInternalError = { fg = palette.bg, bg = palette.orange },
    Pmenu = { fg = palette.fg, bg = palette.bg },
    PmenuSbar = { bg = palette.gray },
    PmenuSel = { fg = palette.bg, bg = palette.olive },
    PmenuThumb = { fg = palette.fg, bg = palette.fg },
    Question = { fg = palette.green, bold = true },
    RedrawDebugClear = { fg = palette.bg, bg = palette.gold },
    RedrawDebugComposed = { fg = palette.bg, bg = palette.olive },
    RedrawDebugNormal = { reverse = true },
    RedrawDebugRecompose = { fg = palette.bg, bg = palette.orange },
    ScrollbarCursor = { fg = palette.bg },
    ScrollbarCursorHandle = { fg = palette.bg, bg = palette.bg, blend = 0 },
    ScrollbarError = { fg = palette.red },
    ScrollbarErrorHandle = { fg = palette.red, bg = palette.bg, blend = 0 },
    ScrollbarGitAdd = { fg = palette.green },
    ScrollbarGitAddHandle = { fg = palette.green, bg = palette.bg, blend = 0 },
    ScrollbarGitChange = { fg = palette.brown },
    ScrollbarGitChangeHandle = { fg = palette.brown, bg = palette.bg, blend = 0 },
    ScrollbarGitDelete = { fg = palette.red },
    ScrollbarGitDeleteHandle = { fg = palette.red, bg = palette.bg, blend = 0 },
    ScrollbarHandle = { bg = palette.bg, blend = 0 },
    ScrollbarHint = { fg = palette.green },
    ScrollbarHintHandle = { fg = palette.green, bg = palette.bg, blend = 0 },
    ScrollbarInfo = { fg = palette.green },
    ScrollbarInfoHandle = { fg = palette.green, bg = palette.bg, blend = 0 },
    ScrollbarMisc = { fg = palette.orange },
    ScrollbarMiscHandle = { fg = palette.orange, bg = palette.bg, blend = 0 },
    ScrollbarSearch = { fg = palette.gold },
    ScrollbarSearchHandle = { fg = palette.gold, bg = palette.bg, blend = 0 },
    ScrollbarWarn = { fg = palette.orange },
    ScrollbarWarnHandle = { fg = palette.orange, bg = palette.bg, blend = 0 },
    Search = { fg = palette.bg, bg = palette.orange },
    SignColumn = { fg = palette.gray, bg = palette.bg },
    Special = { fg = palette.orange },
    SpecialKey = { fg = palette.fg },
    SpellBad = { fg = palette.brown, sp = palette.fg, underline = true },
    SpellCap = { fg = palette.green, sp = palette.fg, underline = true },
    SpellLocal = { fg = palette.orange, sp = palette.fg, underline = true },
    SpellRare = { fg = palette.orange, sp = palette.fg, underline = true },
    Statement = { fg = palette.green, bold = true },
    StatusLine = { fg = palette.fg, bg = palette.bg, bold = true },
    StatusLineNC = { fg = palette.gray, bg = palette.bg, bold = true },
    String = { fg = palette.brown },
    SyntasticErrorSign = { fg = palette.red },
    SyntasticWarningSign = { fg = palette.brown },
    TabLine = { fg = palette.gray, bg = palette.bg },
    TabLineFill = { fg = palette.gold, bg = palette.bg },
    TabLineSel = { fg = palette.bg, bg = palette.olive, bold = true },
    TabLineSelSep = { fg = palette.olive, bg = palette.bg, bold = true },
    TabLineSep = { fg = palette.bg, bg = palette.bg },
    TelescopeBorder = { fg = palette.brown, bg = palette.bg },
    TelescopeMultiIcon = {},
    TelescopeMultiSelection = {},
    TelescopeNormal = {},
    TelescopePreviewBlock = {},
    TelescopePreviewCharDev = {},
    TelescopePreviewDate = {},
    TelescopePreviewDirectory = {},
    TelescopePreviewExecute = {},
    TelescopePreviewGroup = {},
    TelescopePreviewHyphen = {},
    TelescopePreviewMatch = {},
    TelescopePreviewMessage = {},
    TelescopePreviewMessageFillchar = {},
    TelescopePreviewNormal = {},
    TelescopePreviewPipe = {},
    TelescopePreviewRead = {},
    TelescopePreviewSize = {},
    TelescopePreviewSocket = {},
    TelescopePreviewSticky = {},
    TelescopePreviewUser = {},
    TelescopePreviewWrite = {},
    TelescopePromptBorder = { fg = palette.orange, bg = palette.bg },
    TelescopePromptNormal = {},
    TelescopeResultsClass = {},
    TelescopeResultsComment = {},
    TelescopeResultsConstant = {},
    TelescopeResultsDiffUntracked = {},
    TelescopeResultsField = {},
    TelescopeResultsFunction = {},
    TelescopeResultsIdentifier = {},
    TelescopeResultsLineNr = {},
    TelescopeResultsMethod = {},
    TelescopeResultsNormal = {},
    TelescopeResultsNumber = {},
    TelescopeResultsOperator = {},
    TelescopeResultsSpecialComment = {},
    TelescopeResultsStruct = {},
    TelescopeResultsVariable = {},
    TelescopeSelectionCaret = { fg = palette.fg, bg = palette.olive },
    TelescopeTitle = { fg = palette.green, bg = palette.bg },
    TermCursor = { reverse = true },
    Title = { fg = palette.orange, bold = true },
    Todo = { fg = palette.fg, bold = true, underline = true },
    Type = { fg = palette.olive, bold = true },
    Underlined = { fg = palette.olive, underline = true },
    User1 = { fg = palette.fg, bg = palette.orange },
    User2 = { fg = palette.fg, bg = palette.gray },
    User3 = { fg = palette.fg, bg = palette.orange },
    User4 = { fg = palette.fg, bg = palette.bg },
    User5 = { fg = palette.fg, bg = palette.orange },
    User6 = { fg = palette.fg, bg = palette.gold },
    User7 = { fg = palette.fg, bg = palette.olive },
    User8 = { fg = palette.fg, bg = palette.orange },
    User9 = { fg = palette.fg, bg = palette.gray },
    VertSplit = { fg = palette.bg, bg = palette.bg },
    Visual = { fg = palette.bg, bg = palette.olive },
    WarningMsg = { fg = palette.orange },
    WhichKey = { fg = palette.fg, bg = palette.bg },
    WhichKeyBorder = { bg = palette.bg },
    WhichKeyDesc = { fg = palette.green, bg = palette.bg },
    WhichKeyFloat = { bg = palette.bg },
    WhichKeyGroup = { bg = palette.bg },
    WhichKeySeparator = { fg = palette.gold, bg = palette.bg },
    WhichKeyValue = { fg = palette.gold },
    WildMenu = { fg = "black", bg = palette.gold },
    WinBar = { bold = true },
    gitCommitBranch = { fg = palette.orange },
    gitCommitSelectedFile = { fg = palette.green },
    gitCommitSelectedType = { fg = palette.green },
    gitCommitUnmergedFile = { fg = palette.brown },
    gitCommitUnmergedType = { fg = palette.brown },
    htmlArg = { fg = palette.green },
    htmlBold = { bold = true },
    htmlBoldItalic = { bold = true, underline = true },
    htmlBoldUnderline = { bold = true, underline = true },
    htmlBoldUnderlineItalic = { bold = true, underline = true },
    htmlH1 = { bold = true },
    htmlItalic = { underline = true },
    htmlTag = { fg = palette.green },
    htmlTagName = { fg = palette.green },
    htmlUnderline = { underline = true },
    htmlUnderlineItalic = { underline = true },
    lCursor = { fg = palette.bg, bg = palette.fg },
    lessVariable = { fg = palette.orange },
    markdownBold = { bold = true },
    markdownItalic = { underline = true },
    mustacheMarker = { fg = palette.orange },
    mustachePartial = { fg = palette.orange },
    mustacheSection = { bold = true },
    mustacheVariable = { fg = palette.gold },
    mustacheVariableUnescape = { fg = palette.brown },
    netrwClassify = { fg = palette.gray, bold = true },
    netrwExe = { fg = palette.brown },
    phpIdentifier = { fg = palette.orange },
    phpSpecialFunction = { fg = palette.orange },
    shDerefSimple = { fg = palette.orange },
    xmlTag = { fg = palette.olive },

    Character = { link = "Constant" },
    Conceal = { link = "Ignore" },
    Conditional = { link = "Statement" },
    CtrlPLinePre = { link = "Comment" },
    CtrlPMatch = { link = "String" },
    CurSearch = { link = "Search" },
    CursorLineFold = { link = "FoldColumn" },
    CursorLineSign = { link = "SignColumn" },
    Debug = { link = "Special" },
    Define = { link = "PreProc" },
    DiagnosticErrorFloating = { link = "DiagnosticError" },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingWarning = { link = "DiagnosticWarning" },
    DiagnosticHintFloating = { link = "DiagnosticHint" },
    DiagnosticSignOk = { link = "DiagnosticOk" },
    DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
    DiagnosticWarning = { fg = palette.orange },
    DiffSubName = { link = "DiffLine" },
    EndOfBuffer = { link = "NonText" },
    Exception = { link = "Statement" },
    Float = { link = "Number" },
    FloatShadowThrough = { link = "FloatShadow" },
    FloatTitle = { link = "Title" },
    FzfLuaBorder = { link = "Normal" },
    FzfLuaCursor = { link = "Cursor" },
    FzfLuaCursorLine = { link = "CursorLine" },
    FzfLuaCursorLineNr = { link = "CursorLineNr" },
    FzfLuaNormal = { link = "Normal" },
    FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
    FzfLuaScrollFloatFull = { link = "PmenuThumb" },
    FzfLuaSearch = { link = "IncSearch" },
    GitSignsAddNr = { link = "GitSignsAdd" },
    GitSignsChange = { link = "Changed" },
    GitSignsChangeNr = { link = "GitSignsChange" },
    GitSignsCurrentLineBlame = { link = "Comment" },
    GitSignsDeleteNr = { link = "GitSignsDelete" },
    GitSignsStagedChange = { link = "Changed" },
    GitSignsStagedChangeNr = { link = "Changed" },
    IblWhitespace = { link = "IblIndent" },
    Include = { link = "PreProc" },
    Label = { link = "Statement" },
    LazyComment = {},
    LazyCommit = {},
    LazyCommitIssue = {},
    LazyCommitScope = {},
    LazyCommitType = {},
    LazyDimmed = {},
    LazyDir = {},
    LazyLocal = {},
    LazyNoCond = {},
    LazyProgressDone = {},
    LazyProgressTodo = {},
    LazyProp = {},
    LazyReasonCmd = {},
    LazyReasonEvent = {},
    LazyReasonFt = {},
    LazyReasonImport = {},
    LazyReasonKeys = {},
    LazyReasonPlugin = {},
    LazyReasonRuntime = {},
    LazyReasonSource = {},
    LazyReasonStart = {},
    LazyTaskError = {},
    LazyTaskOutput = {},
    LazyUrl = {},
    LazyValue = {},
    LineNrAbove = { link = "LineNr" },
    LineNrBelow = { link = "LineNr" },
    LspCodeLens = { link = "Comment" },
    LspReferenceWrite = { link = "LspReferenceWrite" },
    Macro = { link = "PreProc" },
    MasonError = {},
    MasonHeaderSecondary = { link = "LazyButtonActive" },
    MasonHeading = {},
    MasonHighlightBlock = { link = "LazyButtonActive" },
    MasonHighlightBlockBold = { link = "LazyButtonActive" },
    MasonHighlightBlockBoldSecondary = {},
    MasonHighlightBlockSecondary = {},
    MasonHighlightSecondary = {},
    MasonMutedBlock = { link = "MasonMuted" },
    MasonMutedBlockBold = { link = "MasonHighlight" },
    MasonWarning = {},
    MsgSeparator = { link = "StatusLine" },
    NERDTreeExecFile = { link = "String" },
    NERDTreeHelp = { link = "Comment" },
    NormalFloat = { link = "Pmenu" },
    NotifyBackground = { link = "FloatShadow" },
    NvimArrow = { link = "Delimiter" },
    NvimColon = { link = "Delimiter" },
    NvimComma = { link = "Delimiter" },
    NvimFigureBrace = { link = "NvimInternalError" },
    NvimIdentifier = { link = "Identifier" },
    NvimInvalid = { link = "Error" },
    NvimInvalidSingleQuotedUnknownEscape = { link = "NvimInternalError" },
    NvimInvalidSpacing = { link = "ErrorMsg" },
    NvimNumber = { link = "Number" },
    NvimNumberPrefix = { link = "Type" },
    NvimOptionSigil = { link = "Type" },
    NvimParenthesis = { link = "Delimiter" },
    NvimSingleQuotedUnknownEscape = { link = "NvimInternalError" },
    NvimSpacing = { link = "Normal" },
    NvimString = { link = "String" },
    Operator = { link = "Delimiter" },
    PmenuExtra = { link = "Pmenu" },
    PmenuExtraSel = { link = "PmenuSel" },
    PmenuKind = { link = "Pmenu" },
    PmenuKindSel = { link = "PmenuSel" },
    PreCondit = { link = "PreProc" },
    PreProc = { link = "Keyword" },
    QuickFixLine = { link = "Search" },
    Repeat = { link = "Statement" },
    SpecialChar = { link = "Special" },
    SpecialComment = { link = "Special" },
    StorageClass = { link = "Type" },
    Structure = { link = "Type" },
    Substitute = { link = "Search" },
    Tag = { link = "Special" },
    TelescopeMatching = { link = "Special" },
    TelescopePreviewBorder = { link = "TelescopeBorder" },
    TelescopePreviewLine = { link = "TelescopeSelection" },
    TelescopePreviewLink = {},
    TelescopePreviewTitle = { link = "TelescopeTitle" },
    TelescopePromptCounter = { link = "TelescopeBorder" },
    TelescopePromptPrefix = { link = "TelescopeTitle" },
    TelescopePromptTitle = { link = "TelescopeTitle" },
    TelescopeResultsBorder = { link = "TelescopeBorder" },
    TelescopeResultsFileIcon = { link = "Special" },
    TelescopeResultsTitle = { link = "TelescopeTitle" },
    TelescopeSelection = { link = "Visual" },
    Typedef = { link = "Type" },
    Whitespace = { link = "NonText" },
    WinBarNC = { link = "WinBar" },
    WinSeparator = { link = "VertSplit" },
    gitCommitDiscardedFile = { link = "gitCommitUnmergedFile" },
    gitCommitDiscardedType = { link = "gitCommitUnmergedType" },
    gitCommitFile = { link = "Directory" },
    gitCommitUntrackedFile = { link = "gitCommitUnmergedFile" },
    helpExample = { link = "String" },
    helpHeadline = { link = "Title" },
    helpHyperTextEntry = { link = "Statement" },
    helpHyperTextJump = { link = "Underlined" },
    helpSectionDelim = { link = "Comment" },
    helpURL = { link = "Underlined" },
    htmlEndTag = { link = "htmlTag" },
    htmlLink = { link = "Underlined" },
    javaScript = { link = "Normal" },
    javaScriptBraces = { link = "Delimiter" },
    lessVariableValue = { link = "Normal" },
    markdownCodeBlock = { link = "String" },
    markdownCodeDelimiter = { link = "NonText" },
    markdownHeadingRule = { link = "NonText" },
    markdownLinkDelimiter = { link = "Delimiter" },
    markdownURLDelimiter = { link = "Delimiter" },
    phpDefine = { link = "Statement" },
    phpHereDoc = { link = "String" },
    phpVarSelector = { link = "phpIdentifier" },
    rubyConstant = { link = "Constant" },
    rubyDefine = { link = "Statement" },
    rubyInstanceVariable = { link = "Number" },
    rubyLocalVariableOrMethod = { link = "Identifier" },
    shDerefVar = { link = "shDerefSimple" },
    vimContinue = { link = "Delimiter" },
    vimHiAttrib = { link = "Constant" },
    vimSetSep = { link = "Delimiter" },
    xmlAttrib = { link = "xmlTag" },
    xmlEndTag = { link = "xmlTag" },
    xmlEqual = { link = "xmlTag" },
    xmlString = { link = "xmlTag" },
    xmlTagName = { link = "xmlTag" },

    -- Treesitter
    ["@number"] = { link = "Number" },
    ["@keyword"] = { link = "Keyword" },
    ["@variable"] = { link = "Identifier" },
    ["@text.reference"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@parameter"] = { link = "Identifier" },
    ["@namespace"] = { link = "Identifier" },
    ["@lsp.type.variable"] = { link = "Identifier" },
    ["@lsp.type.property"] = { link = "Identifier" },
    ["@lsp.type.parameter"] = { link = "Identifier" },
    ["@field"] = { link = "Identifier" },
    ["@method"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.decorator"] = { link = "Function" },
    ["@function"] = { link = "Function" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@constant"] = { link = "Constant" },
    ["@text.literal"] = { link = "Comment" },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@comment"] = { link = "Comment" },
    ["@boolean"] = { link = "Boolean" },
    ["@preproc"] = { link = "PreProc" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.underline"] = { link = "Underlined" },
    ["@type"] = { link = "Type" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.title"] = { link = "Title" },
    ["@string"] = { link = "String" },
    ["@function.builtin"] = { link = "Special" },
    ["@constructor"] = { link = "Special" },
    ["@constant.builtin"] = { link = "Special" },

  }
end

return M
